# Numpy

In [2]:
import numpy as np 


In [5]:
a = np.array([1,234,4,5,5])

In [22]:
type(a)

type(np.ones(1))
mas = np.arange(0, 20, 2) 
mas_2 = np.linspace(0,1, 20) #создает 20 числе в диапазоне от 0 до 1
mas_3 = np.random.random((3,3)) #uniformly distributed


In [25]:
print(mas,'\n\n', mas_2,'\n\n', mas_3)

[ 0  2  4  6  8 10 12 14 16 18] 

 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ] 

 [[0.73477283 0.85252675 0.44646671]
 [0.18033497 0.56340525 0.65945188]
 [0.77775363 0.21467366 0.7558563 ]]


# Numpy Array Attributes

In [69]:
np.random.seed()
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))


In [70]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("dtype", x3.dtype)
print("itemsize", x3.itemsize)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype int32
itemsize 4


### Multidimensial subarrays

In [71]:
# Multidimensial subarrays
print(x2, '\n')
print(x2[:2, :3], '\n')
print("the first raw", x2[0,:], '\t', x2[0])
#Это очень полезно понимать, смотри мы меняем часть. ТО есть при слайсе, не создается
#При слайсе не создается копия. Это прямо круто!!!


[[1 5 4 4]
 [6 9 2 3]
 [4 8 7 4]] 

[[1 5 4]
 [6 9 2]] 

the first raw [1 5 4 4] 	 [1 5 4 4]


In [83]:
x2_sub = x2[:2, :2]
x2_sub[:] = -1
print(x2_sub)
print(x2) 

[[-1 -1]
 [-1 -1]]
[[-1 -1  4  4]
 [-1 -1  2  3]
 [ 0  0  0  4]]


In [84]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[:] = 100
print(x2_sub_copy)
x2 # Ничего не поменялось 

[[100 100]
 [100 100]]


array([[-1, -1,  4,  4],
       [-1, -1,  2,  3],
       [ 0,  0,  0,  4]])

In [86]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array concatenation

In [103]:
x = np.array([1,2,4])
y = np.array([3,2,1])
np.concatenate([x, y])
grid_0 = np.concatenate([grid, grid], axis=0)
grid_1 = np.concatenate([grid, grid], axis=1)
print(grid_0.shape, grid_1.shape)

(6, 3) (3, 6)


In [107]:
print(np.vstack([x,y]))
np.vstack([x,grid])

[[1 2 4]
 [3 2 1]]


array([[1, 2, 4],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
x= np.arange(1,10)
x1, x2, x3 = np.split(x, [2,4])
print(x1, x2, x3)

[1 2] [3 4] [5 6 7 8 9]


In [121]:
grid = np.arange(16).reshape((4,4))
print(grid, grid.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)


In [120]:
upper, lower = np.vsplit(grid, [2])
print(upper,upper.shape, '\n\n', lower, lower.shape)

[[0 1 2 3]
 [4 5 6 7]] (2, 4) 

 [[ 8  9 10 11]
 [12 13 14 15]] (2, 4)


In [123]:
left, right = np.hsplit(grid, [2])
print(left,left.shape, '\n\n', right, right.shape)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] (4, 2) 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] (4, 2)
