In [1]:
%matplotlib inline
import torch


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
torch.__version__

'1.4.0'

In [3]:
from __future__ import print_function
import torch
import matplotlib.pyplot as plt

Construct a randomly initialized matrix:



In [4]:
x_uni = torch.rand(5, 3)
x_norm = torch.randn(5, 3)
print(x_uni,'\n', x_norm)


tensor([[0.4457, 0.2697, 0.3180],
        [0.3953, 0.3772, 0.2826],
        [0.1313, 0.7410, 0.0793],
        [0.5917, 0.7225, 0.2506],
        [0.6530, 0.5260, 0.0892]]) 
 tensor([[-0.3620,  1.6566, -0.2434],
        [-1.9767,  0.8926,  1.5425],
        [ 0.4969, -0.2126, -0.9886],
        [ 0.9527,  0.3141, -0.7365],
        [ 0.8532,  0.9500, -0.1238]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x.size())

torch.Size([5, 3])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4722, -0.0538, -0.3207],
        [ 0.1570, -0.5530, -0.4076],
        [-1.2306, -1.1400,  0.4040],
        [ 1.4220,  0.5503, -0.1304],
        [-0.8816, -0.1024,  2.0294]])


Get its size:



In [8]:
a, b = x.size()
a, b

(5, 3)

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.6649,  0.6429,  0.4691],
        [ 0.5054, -0.3943, -0.1046],
        [-1.1607, -0.2513,  0.9205],
        [ 2.2670,  1.4563, -0.1243],
        [ 0.0902,  0.1120,  2.0321]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[-0.6649,  0.6429,  0.4691],
        [ 0.5054, -0.3943, -0.1046],
        [-1.1607, -0.2513,  0.9205],
        [ 2.2670,  1.4563, -0.1243],
        [ 0.0902,  0.1120,  2.0321]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.6649,  0.6429,  0.4691],
        [ 0.5054, -0.3943, -0.1046],
        [-1.1607, -0.2513,  0.9205],
        [ 2.2670,  1.4563, -0.1243],
        [ 0.0902,  0.1120,  2.0321]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.6649,  0.6429,  0.4691],
        [ 0.5054, -0.3943, -0.1046],
        [-1.1607, -0.2513,  0.9205],
        [ 2.2670,  1.4563, -0.1243],
        [ 0.0902,  0.1120,  2.0321]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.0538, -0.5530, -1.1400,  0.5503, -0.1024])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1841])
0.1841283142566681


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
import numpy as np

In [19]:
mas_np = np.array([1,2,3,4,5])
mas_torch = torch.from_numpy(mas_np)
#print(mas_np, mas_torch)
mas_torch_np = mas_torch.numpy()
print('torch:',mas_torch,'\nnumpy:', mas_torch_np)
mas_torch_np[0] = 100
print('torch:',mas_torch,'\nnumpy:', mas_torch_np,'\nnumpy first:', mas_np)

torch: tensor([1, 2, 3, 4, 5], dtype=torch.int32) 
numpy: [1 2 3 4 5]
torch: tensor([100,   2,   3,   4,   5], dtype=torch.int32) 
numpy: [100   2   3   4   5] 
numpy first: [100   2   3   4   5]


See how the numpy array changed in value.



In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [22]:
torch.cuda.is_available()

True

In [23]:
import time


In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
print("Multiple 2 tensors: [10000, 10000] * [10000, 10000]")
x = torch.rand(10000,10000)
y = torch.ones_like(x)
start_cpu = time.time()
z = torch.matmul(x, y)

time_cpu = time.time() - start_cpu
print('Speed on CPU:',  time_cpu)

device = torch.device("cuda")          # a CUDA device object 
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device) 
start = time.time()
z1 = torch.matmul(x, y)

time_gpu = time.time()-start
print("Speed on GPU:", time_gpu)

Multiple 2 tensors: [10000, 10000] * [10000, 10000]
Speed on CPU: 17.460022926330566
Speed on GPU: 0.3541221618652344
